export default {
    THEME_INIT: "THEME_INIT",
    THEME_CHANGE: "THEME_CHANGE",
    JOINEDLIST_REFRESH: "JOINEDLIST_REFRESH",
    JOINEDLIST_REFRESH_FAILED: "JOINEDLIST_REFRESH_FAILED",
    JOINEDLIST_REFRESH_SUCCESS: "JOINEDLIST_REFRESH_SUCCESS",
    JOINEDLIST_LOAD_MORE_FAILED: "JOINEDLIST_LOAD_MORE_FAILED",
    JOINEDLIST_LOAD_MORE_SUCCESS: "JOINEDLIST_LOAD_MORE_SUCCESS",
    MAINTASK_CHANGE: "MAINTASK_CHANGE",
    MAINTASK_DETAIL_CHANGE: "MAINTASK_DETAIL_CHANGE",
<<<<<<< HEAD
    ADD_NEW_COORDINATE: "ADD_NEW_COORDINATE",
    USER_SET_USERNAME:"USER_SET_USERNAME",
    USER_SET_PASSWORD:"USER_SET_PASSWORD",
    USER_SET_TOKEN:"USER_SET_TOKEN",
=======
    USER_SET_USERNAME:"USER_SET_USERNAME",
    USER_SET_PASSWORD:"USER_SET_PASSWORD",
    USER_SET_TOKEN:"USER_SET_TOKEN",
    ADD_NEW_COORDINATE: "ADD_NEW_COORDINATE",
>>>>>>> e964001f7cd6afdf0a9b42ff943d3fde9e3fc1c2
};
