export default {
    THEME_INIT: "THEME_INIT",
    THEME_CHANGE: "THEME_CHANGE",
    JOINEDLIST_REFRESH: "JOINEDLIST_REFRESH",
    JOINEDLIST_REFRESH_FAILED: "JOINEDLIST_REFRESH_FAILED",
    JOINEDLIST_REFRESH_SUCCESS: "JOINEDLIST_REFRESH_SUCCESS",
    JOINEDLIST_LOAD_MORE_FAILED: "JOINEDLIST_LOAD_MORE_FAILED",
    JOINEDLIST_LOAD_MORE_SUCCESS: "JOINEDLIST_LOAD_MORE_SUCCESS",
    MAINTASK_CHANGE: "MAINTASK_CHANGE",
    MAINTASK_DETAIL_CHANGE: "MAINTASK_DETAIL_CHANGE",
    ADD_NEW_COORDINATE: "ADD_NEW_COORDINATE",
};
